### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by Keko-94** [Lupennat/nova-better-lens#5]
Hello,

Thank you for your package, is it possible to hide the back button when you are on a lens ?
I used the Hide From Toolbar to hide the lens from the main resource, but the back button still appears there.

Thanks

**Comment by Lupennat** [comment]
@Keko-94 what do you mean "back button still appears", do you mean the main resource link on breadcrumbs or something else? I don't understand which button you are referring to ...

**Comment by Keko-94** [comment]
I am sorry, I checked again and this is not an issue related to your package, I use another package "nova back button" and the problem comes from there.

**Comment by Lupennat** [comment]
Ok thanks for the feedback
